### PR TITLE
merge: master <- develop

### PR DESCRIPTION
**Pull request by lukewhrit**
## Changes of note

* Return a hash of content instead of content
* Added route validators
* Added endpoint for getting plain text version of document
* Added endpoint to verify if a document exists
* `/api/v1/document/` -> `/api/v1/documents/`

### CODE REVIEW

**Comment by lukewhrit** [comment]
ESLint failing is once again due to deleted files.

**Comment by jackiedorland** [comment]
Can't merge this, due to those checks. Disable them and try again.

**Review by jackiedorland — APPROVED** [review]
:+1:

**Comment by jackiedorland** [comment]
Nevermind

**Pull request merged**
