### PR TITLE
docs: new CONTRIBUTORS file

### LINKED ISSUE #9: Fully completed GitHub community profile
So far we need to complete: 

- [x] Description
- [x] README.md (continuously changing) 
- [x] [Code of Conduct](https://github.com/spacebin-for-astronauts/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] CONTRIBUTORS.md ( #8 )
- [x] Issue templates (Bug, Feature Request)
- [x] Pull Request templates

### PR DESCRIPTION
**Pull request by jackiedorland**
I'm trying to make this as clean as possible; as of right now we need to complete more of the project to finish this up.

Once more people start seeing the project and it's in `alpha` stages, we'll be good to go on finishing this.

### CODE REVIEW

**Comment by lukewhrit** [comment]
I think we should be good to merge after `ec8583d`. @heyitspuggo want to review?

**Comment by jackiedorland** [comment]
Looks good. Let me look over it.

**Review by jackiedorland — COMMENTED** [review]
One more thing: make sure to add that we will be running over each commit with an Action that lints it. If the linting fails, the PR will be requested to be fixed, @324Luke

**Comment by jackiedorland** [comment]
Oh and: Please add a Verified SSH key to your profile. Soon enough, I'll make it a requirement.

**Comment by lukewhrit** [comment]
> One more thing: make sure to add that we will be running over each commit with an Action that lints it. If the linting fails, the PR will be requested to be fixed, @324Luke

@heyitspuggo I'll add this to the document.

**Comment by lukewhrit** [comment]
> Oh and: Please add a Verified SSH key to your profile. Soon enough, I'll make it a requirement.

Sure.

**Review by lukewhrit — APPROVED** [review]

**Pull request merged**
